spring:
  kafka:
    bootstrap-servers: 120.79.77.11:9092,120.79.77.11:9093,120.79.77.11:9094
    consumer:
      client-id: 1
      group-id: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000
datasource:
  url: jdbc:mysql://120.79.77.11:3784/demorocket
  username: root
  password: HaoHao_112
  driverName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:com/tml/springconsumer/mapper/*
